### ISSUE TITLE
Grimm Child has desapear from the screen

### ISSUE THREAD

**Issue by PomboN9878** [ilcheese2/CarefreeGrimm#1]
Hi, when I installed this mod, I didn't notice that at the start of the ritual, the Grimm child disappears and appears in specific rooms in the game. I like the companion of the Grimm child; without the Grimm child, some of the animations don't have any meaning – they're just weird. An example is the first fight with the troupe master, where he opens his mantle and waits for about 3 seconds before disappearing, rendering his movements useless. As I was saying, I just want the Grimm child back on the scree.

**Comment by ilcheese2** [comment]
When I created the mod, I forgot about the grimmchild state before choosing either end charm. I'll fix this soon, hopefully.

**Comment by ilcheese2** [comment]
In honor of getting 20,000 downloads, I will fix this sooner.

**Comment by ilcheese2** [comment]
Fixed in latest version
